version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  steps:
    # Checkout the code as the first step.
    - checkout
    # Next, the node orb's install-packages step will install the dependencies from a package.json.
    # The orb install-packages step will also automatically cache them for faster future runs.
    - node/install-packages:
        pkg-manager: yarn